In [2]:
import matplotlib.pyplot as plt
import numpy as np
from mpl_toolkits.mplot3d import Axes3D
import scipy as sp
import sympy as sy
sy.init_printing() 

In [3]:
np.set_printoptions(precision=3)
np.set_printoptions(suppress=True)

In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all" # display multiple results

In [5]:
def round_expr(expr, num_digits):
    return expr.xreplace({n : round(n, num_digits) for n in expr.atoms(sy.Number)})

# <font face="gotham" color="purple"> 矩阵运算</font>

矩阵加法运算是直接的：
1. $A+ B= B+ A$
2. $(A+B)+ C=A+(B+C)$
3. $c(A+B)=cA+cB$
4. $(c+d)A=cA+c{D}$
5. $c(dA)=(cd)A$
6. $A+{0}=A$, 其中$0$是零矩阵
7. 对于任意的$A$, 存在一个$- A$, 使得 $ A+(- A)=0$.

它们看起来就像它们看起来那样明显，因此没有提供证明。而矩阵乘法的性质是：
1. $ A({BC})=({AB}) C$
2. $c({AB})=(cA)B=A(cB)$
3. $A(B+ C)={AB}+{AC}$
4. $(B+C)A={BA}+{CA}$

请注意，我们需要区分两种乘法，**哈达玛德乘法**（按元素乘法）和**矩阵乘法**：

In [6]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [7]:
A*B # 哈达玛逐元素乘积

array([[ 5, 12],
       [21, 32]])

In [8]:
A@B # 矩阵乘积

array([[19, 22],
       [43, 50]])

我们明确展示矩阵乘法规则:

In [9]:
np.sum(A[0,:]*B[:,0]) # (1, 1)
np.sum(A[1,:]*B[:,0]) # (2, 1)
np.sum(A[0,:]*B[:,1]) # (1, 2)
np.sum(A[1,:]*B[:,1]) # (2, 2)

19

43

22

50

## <font face="gotham" color="purple"> SymPy 演示：加法 </font>

让我们将所有字母定义为符号，以防我们可能会重复使用它们。

In [10]:
a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z = sy.symbols('a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z', real = True)

In [11]:
A = sy.Matrix([[a, b, c], [d, e, f]])
A + A
A - A

⎡2⋅a  2⋅b  2⋅c⎤
⎢             ⎥
⎣2⋅d  2⋅e  2⋅f⎦

⎡0  0  0⎤
⎢       ⎥
⎣0  0  0⎦

In [12]:
B = sy.Matrix([[g, h, i], [j, k, l]])
A + B
A - B

⎡a + g  b + h  c + i⎤
⎢                   ⎥
⎣d + j  e + k  f + l⎦

⎡a - g  b - h  c - i⎤
⎢                   ⎥
⎣d - j  e - k  f - l⎦

## <font face="gotham" color="purple"> SymPy 演示：乘法 </font>

矩阵乘法规则可以通过使用符号来清晰地理解。

In [13]:
A = sy.Matrix([[a, b, c], [d, e, f]])
B = sy.Matrix([[g, h, i], [j, k, l], [m, n, o]])
A
B

⎡a  b  c⎤
⎢       ⎥
⎣d  e  f⎦

⎡g  h  i⎤
⎢       ⎥
⎢j  k  l⎥
⎢       ⎥
⎣m  n  o⎦

In [14]:
AB = A*B; AB

⎡a⋅g + b⋅j + c⋅m  a⋅h + b⋅k + c⋅n  a⋅i + b⋅l + c⋅o⎤
⎢                                                 ⎥
⎣d⋅g + e⋅j + f⋅m  d⋅h + e⋅k + f⋅n  d⋅i + e⋅l + f⋅o⎦

## <font face="gotham" color="purple"> 交换性 </font>

矩阵乘法通常不具有交换性，即 $AB \neq BA$。例如，考虑矩阵 $A$ 和 $B$：

In [15]:
A = sy.Matrix([[3, 4], [7, 8]])
B = sy.Matrix([[5, 3], [2, 1]])
A*B
B*A

⎡23  13⎤
⎢      ⎥
⎣51  29⎦

⎡36  44⎤
⎢      ⎥
⎣13  16⎦

我们如何找到一个具有交换性的矩阵？

In [16]:
A = sy.Matrix([[a, b], [c, d]])
B = sy.Matrix([[e, f], [g, h]])
A*B
B*A

⎡a⋅e + b⋅g  a⋅f + b⋅h⎤
⎢                    ⎥
⎣c⋅e + d⋅g  c⋅f + d⋅h⎦

⎡a⋅e + c⋅f  b⋅e + d⋅f⎤
⎢                    ⎥
⎣a⋅g + c⋅h  b⋅g + d⋅h⎦

要证明 ${AB} = {BA}$，我们需要证明 ${AB} - {BA} = 0$。

In [17]:
M = A*B - B*A; M

⎡      b⋅g - c⋅f         a⋅f - b⋅e + b⋅h - d⋅f⎤
⎢                                             ⎥
⎣-a⋅g + c⋅e - c⋅h + d⋅g       -b⋅g + c⋅f      ⎦

那意味着

\begin{align}
b g - c f&=0 \\
 a f - b e + b h - d f&=0\\
- a g + c e - c h + d g&=0 \\
- b g + c f&=0
\end{align}

如果我们将$a，b，c，d$视为系统的系数，我们可以提取一个增广矩阵

In [18]:
A_aug = sy.Matrix([[0, -c, b, 0], [-b, a-d, 0, b], [c, 0, d -a, -c], [0, c, -b, 0]]); A_aug

⎡0    -c      b     0 ⎤
⎢                     ⎥
⎢-b  a - d    0     b ⎥
⎢                     ⎥
⎢c     0    -a + d  -c⎥
⎢                     ⎥
⎣0     c      -b    0 ⎦

执行高斯-约当消元直到得到行简化形式。

In [19]:
A_aug.rref()

⎛⎡        a   d    ⎤        ⎞
⎜⎢1  0  - ─ + ─  -1⎥        ⎟
⎜⎢        c   c    ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢        -b       ⎥        ⎟
⎜⎢0  1    ───    0 ⎥, (0, 1)⎟
⎜⎢         c       ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎜⎢0  0     0     0 ⎥        ⎟
⎜⎢                 ⎥        ⎟
⎝⎣0  0     0     0 ⎦        ⎠

通解是
\begin{align}
e - \frac{a-d}cg - h &=0\\
f - \frac{b}{c} & =0\\
g &= free\\
h & =free
\end{align}

如果我们设置系数 $a = 10, b = 12, c = 20, d = 8$, or $ A = \left[\begin{matrix}10 & 12\\20 & 8\end{matrix}\right]$ 那么通解变为


\begin{align}
e - .1g - h &=0\\
f - .6 & =0\\
g &= free\\
h & =free
\end{align}
然后尝试当 $g = h = 1$ 时的特解
\begin{align}
e  &=1.1\\
f & =.6\\
g &=1 \\
h & =1
\end{align}

这是 $A$ 的一个可交换矩阵，我们表示为 $C$。

In [20]:
C = sy.Matrix([[1.1, .6], [1, 1]]);C

⎡1.1  0.6⎤
⎢        ⎥
⎣ 1    1 ⎦

现在我们可以看到 ${AC}={CA}$。

In [21]:
A = sy.Matrix([[10, 12], [20, 8]])
A*C
C*A

⎡23.0  18.0⎤
⎢          ⎥
⎣30.0  20.0⎦

⎡23.0  18.0⎤
⎢          ⎥
⎣ 30    20 ⎦

# <font face="gotham" color="purple"> 矩阵的转置 </font>

矩阵 $A_{n\times m}$ 及其转置是

In [22]:
A = np.array([[1, 2, 3], [4, 5, 6]]); A
A.T # transpose

array([[1, 2, 3],
       [4, 5, 6]])

array([[1, 4],
       [2, 5],
       [3, 6]])

In [23]:
A = sy.Matrix([[1, 2, 3], [4, 5, 6]]); A
A.transpose()

⎡1  2  3⎤
⎢       ⎥
⎣4  5  6⎦

⎡1  4⎤
⎢    ⎥
⎢2  5⎥
⎢    ⎥
⎣3  6⎦

转置的性质包括
1. $(A^T)^T$
2. $(A+B)^T=A^T+B^T$
3. $(cA)^T=cA^T$
4. $(AB)^T=B^TA^T$

我们可以用 SymPy 来展示为什么最后一个性质成立，定义 $A$ 和 $B$，将它们相乘，然后对结果进行转置，即表示为 $(AB)^T$。

In [24]:
A = sy.Matrix([[a, b], [c, d], [e, f]])
B = sy.Matrix([[g, h, i], [j, k, l]])
AB = A*B
AB_tr = AB.transpose(); AB_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

先对它们各自进行转置，然后相乘，这表示为 $B^TA^T$。

In [25]:
B_tr_A_tr = B.transpose()*A.transpose()
B_tr_A_tr

⎡a⋅g + b⋅j  c⋅g + d⋅j  e⋅g + f⋅j⎤
⎢                               ⎥
⎢a⋅h + b⋅k  c⋅h + d⋅k  e⋅h + f⋅k⎥
⎢                               ⎥
⎣a⋅i + b⋅l  c⋅i + d⋅l  e⋅i + f⋅l⎦

看它们是否相等

In [26]:
AB_tr - B_tr_A_tr

⎡0  0  0⎤
⎢       ⎥
⎢0  0  0⎥
⎢       ⎥
⎣0  0  0⎦

# <font face="gotham" color="purple"> 单位矩阵 </font>

这是一个单位矩阵 $I_5$

In [27]:
sy.eye(5)

⎡1  0  0  0  0⎤
⎢             ⎥
⎢0  1  0  0  0⎥
⎢             ⎥
⎢0  0  1  0  0⎥
⎢             ⎥
⎢0  0  0  1  0⎥
⎢             ⎥
⎣0  0  0  0  1⎦

单位矩阵的性质：

$$
AI=IA = A
$$

让我们生成 $I$ 和 $A$，并展示它是否成立

In [28]:
I = np.eye(5); I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
A = np.around(np.random.rand(5, 5)*100); A # 生成一个随机矩阵

array([[55., 86., 26., 65., 71.],
       [94., 87., 58., 91., 28.],
       [ 7., 70., 79., 74., 39.],
       [33., 30., 39., 15., 44.],
       [53., 16.,  8., 61., 34.]])

显然它成立

In [30]:
A@I - I@A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

# <font face="gotham" color="purple"> 初等矩阵 </font>

**初等矩阵**是从单位矩阵上进行单个初等行操作得到的矩阵。例如：

\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}\begin{array}{c}R_1\leftrightarrow R_2\\\\\end{array}\quad\Longrightarrow\quad\begin{bmatrix}0&1&0\\1&0&0\\0&0&1\end{bmatrix}

其中 $R_1\leftrightarrow R_2$ 表示交换第 $1$ 行和第 $2$ 行，我们用 ${E}$ 表示变换后的矩阵，然后将 $E$ 左乘到矩阵 $A$ 上。首先生成矩阵 $A$。

In [31]:
A = sy.randMatrix(3, percent = 80); A # 生成一个 $80\%$ 的元素为非零的随机矩阵

⎡6   62  0 ⎤
⎢          ⎥
⎢14  46  66⎥
⎢          ⎥
⎣68  44  0 ⎦

创建一个进行 $R_1\leftrightarrow R_2$ 行变换的初等矩阵

In [32]:
E = sy.Matrix([[0, 1, 0], [1, 0, 0], [0, 0, 1]]);E

⎡0  1  0⎤
⎢       ⎥
⎢1  0  0⎥
⎢       ⎥
⎣0  0  1⎦

结果表明，通过将 $E$ 左乘到 $A$ 上，$A$ 也会交换行 $1$ 和 $2$。

In [33]:
E*A

⎡14  46  66⎤
⎢          ⎥
⎢6   62  0 ⎥
⎢          ⎥
⎣68  44  0 ⎦

在单位矩阵中将一行的倍数加到另一行上也会得到一个初等矩阵。

\begin{bmatrix}1&0&0\\0&1&0\\0&0&1\end{bmatrix}R_3-7R_1\quad\longrightarrow\begin{bmatrix}1&0&0\\0&1&0\\-7&0&1\end{bmatrix}


让我们用 SymPy 来验证。

In [34]:
A = sy.randMatrix(3, percent = 80); A
E = sy.Matrix([[1, 0, 0], [0, 1, 0], [-7, 0, 1]]); E

⎡36  99  56⎤
⎢          ⎥
⎢71  60  0 ⎥
⎢          ⎥
⎣0   66  68⎦

⎡1   0  0⎤
⎢        ⎥
⎢0   1  0⎥
⎢        ⎥
⎣-7  0  1⎦

In [35]:
E*A

⎡ 36    99    56 ⎤
⎢                ⎥
⎢ 71    60    0  ⎥
⎢                ⎥
⎣-252  -627  -324⎦

我们也可以通过对 $A$ 执行显式的行操作来展示这一点。

In [36]:
EA = sy.matrices.MatrixBase.copy(A)
EA[2,:]=-7*EA[0,:]+EA[2,:]
EA

⎡ 36    99    56 ⎤
⎢                ⎥
⎢ 71    60    0  ⎥
⎢                ⎥
⎣-252  -627  -324⎦

在下一节中，我们将看到一个重要的结论，即可逆矩阵是一系列初等矩阵的乘积。

# <font face="gotham" color="purple"> 逆矩阵</font>

如果 ${AB}={BA}=\mathbf{I}$，则 $B$ 被称为矩阵 $A$ 的逆，记作 $B=A^{-1}$。

NumPy 提供了方便的函数 np.linalg.inv() 用于计算逆矩阵。生成 $A$

In [37]:
A = np.round(10*np.random.randn(5,5)); A

array([[-13.,  -8., -13.,  23.,   2.],
       [-25.,  -2.,  -7.,  -7.,  -9.],
       [ -6.,  -2.,   4.,  -1.,   6.],
       [ -8., -23.,   3.,  14.,   7.],
       [ -8.,  12., -10.,  -1.,  -2.]])

In [38]:
Ainv = np.linalg.inv(A); Ainv

array([[-0.061, -0.038, -0.101,  0.08 ,  0.09 ],
       [ 0.106,  0.013,  0.133, -0.168, -0.144],
       [ 0.184,  0.058,  0.233, -0.284, -0.373],
       [ 0.161,  0.022,  0.123, -0.189, -0.232],
       [-0.122, -0.069, -0.025,  0.182,  0.252]])

验证它们是否真的是彼此的逆

In [39]:
A@Ainv

array([[ 1.,  0.,  0., -0., -0.],
       [ 0.,  1.,  0., -0., -0.],
       [ 0.,  0.,  1.,  0., -0.],
       [ 0., -0., -0.,  1.,  0.],
       [-0., -0.,  0., -0.,  1.]])

 ```-0.``` 意味着小数点后还有更多的数字，但这里被省略了。

## <font face="gotham" color="purple"> $[A\,|\,I]\sim [I\,|\,A^{-1}]$ 算法 </font>

计算逆矩阵的一个便利方法是，我们可以构造一个增广矩阵 $[ A|\mathbf{I}]$，然后将一系列的 $E$，即初等行操作，与矩阵 $A$ 相乘，直到 $A$ 变成行简化形式。如果满秩，则意味着 $A \rightarrow \mathbf{I}$。然后增广矩阵右侧的 $\mathbf{I}$ 会自动转换为 $A^{-1}$。

我们可以使用 SymPy 的 .rref() 函数在增广矩阵 $[A|I]$ 上进行展示。

In [40]:
AI = np.hstack((A, I)) # 将矩阵 $A$ 和 $\mathbf{I}$ 水平堆叠
AI = sy.Matrix(AI); AI

⎡-13.0  -8.0   -13.0  23.0  2.0   1.0   0    0    0    0 ⎤
⎢                                                        ⎥
⎢-25.0  -2.0   -7.0   -7.0  -9.0   0   1.0   0    0    0 ⎥
⎢                                                        ⎥
⎢-6.0   -2.0    4.0   -1.0  6.0    0    0   1.0   0    0 ⎥
⎢                                                        ⎥
⎢-8.0   -23.0   3.0   14.0  7.0    0    0    0   1.0   0 ⎥
⎢                                                        ⎥
⎣-8.0   12.0   -10.0  -1.0  -2.0   0    0    0    0   1.0⎦

In [41]:
AI_rref = AI.rref(); AI_rref

⎛⎡1  0  0  0  0  -0.0611548106218399  -0.038496410105614   -0.101158241237635 
⎜⎢                                                                            
⎜⎢0  1  0  0  0   0.105948851152115   0.0131343576171923    0.132646393360942 
⎜⎢                                                                            
⎜⎢0  0  1  0  0   0.184403767142869   0.0582469553284815    0.232836710856265 
⎜⎢                                                                            
⎜⎢0  0  0  1  0   0.160601828028131   0.0217599059031096    0.122742532284545 
⎜⎢                                                                            
⎝⎣0  0  0  0  1  -0.122007400328359   -0.0693229434683526  -0.0250434953074077

  0.0804316041396097  0.0901149256291504⎤                 ⎞
                                        ⎥                 ⎟
  -0.168328881700932  -0.144367663995687⎥                 ⎟
                                        ⎥                 ⎟
  -0.283801775752081  -0.372503614398785⎥, (0, 1

Extract the RHS block, this is the $A^{-1}$.

In [42]:
Ainv = AI_rref[0][:,5:];Ainv # 提取右侧的 RHS 块

⎡-0.0611548106218399  -0.038496410105614   -0.101158241237635   0.080431604139
⎢                                                                             
⎢ 0.105948851152115   0.0131343576171923    0.132646393360942   -0.16832888170
⎢                                                                             
⎢ 0.184403767142869   0.0582469553284815    0.232836710856265   -0.28380177575
⎢                                                                             
⎢ 0.160601828028131   0.0217599059031096    0.122742532284545   -0.18932098311
⎢                                                                             
⎣-0.122007400328359   -0.0693229434683526  -0.0250434953074077  0.181969663554

6097  0.0901149256291504⎤
                        ⎥
0932  -0.144367663995687⎥
                        ⎥
2081  -0.372503614398785⎥
                        ⎥
6469  -0.23171359258987 ⎥
                        ⎥
608   0.251709181798133 ⎦

我在文件顶部编写了一个函数，将浮点数四舍五入到第四位小数，但这并非绝对必要。

In [43]:
round_expr(Ainv, 4) 

⎡-0.0612  -0.0385  -0.1012  0.0804   0.0901 ⎤
⎢                                           ⎥
⎢0.1059   0.0131   0.1326   -0.1683  -0.1444⎥
⎢                                           ⎥
⎢0.1844   0.0582   0.2328   -0.2838  -0.3725⎥
⎢                                           ⎥
⎢0.1606   0.0218   0.1227   -0.1893  -0.2317⎥
⎢                                           ⎥
⎣-0.122   -0.0693  -0.025    0.182   0.2517 ⎦

我们可以验证是否 $AA^{-1}=\mathbf{I}$

In [44]:
A = sy.Matrix(A)
round_expr(A*Ainv, 4) 

⎡1.0   0    0    0    0 ⎤
⎢                       ⎥
⎢ 0   1.0   0    0    0 ⎥
⎢                       ⎥
⎢ 0    0   1.0   0    0 ⎥
⎢                       ⎥
⎢ 0    0    0   1.0   0 ⎥
⎢                       ⎥
⎣ 0    0    0    0   1.0⎦

我们得到了 $\mathbf{I}$，这意味着右侧的块确实是 $A^{-1}$。

## <font face="gotham" color="purple"> 存在逆的一个例子</font>

确定 $\lambda$ 的值，使得矩阵
$$A=\left[ \begin{matrix}3 &\lambda &1\cr 2 & -1 & 6\cr 1 & 9 & 4\end{matrix}\right]$$
不可逆。

依然使用 SymPy 来解决这个问题。

In [45]:
lamb = sy.symbols('lamda') # SymPy 会自动将希腊字母渲染成 LaTeX。
A = np.array([[3, lamb, 1], [2, -1, 6], [1, 9, 4]])
I = np.eye(3); A

array([[3, lamda, 1],
       [2, -1, 6],
       [1, 9, 4]], dtype=object)

构建增广矩阵。

In [46]:
AI = np.hstack((A, I))
AI = sy.Matrix(AI); AI

⎡3  λ   1  1.0   0    0 ⎤
⎢                       ⎥
⎢2  -1  6   0   1.0   0 ⎥
⎢                       ⎥
⎣1  9   4   0    0   1.0⎦

In [47]:
AI_rref = AI.rref()
AI_rref

⎛⎡             116.0       8.0⋅λ - 18.0  -12.0⋅λ - 2.0⎤           ⎞
⎜⎢1  0  0  ─────────────  ─────────────  ─────────────⎥           ⎟
⎜⎢         4.0⋅λ + 310.0  4.0⋅λ + 310.0  4.0⋅λ + 310.0⎥           ⎟
⎜⎢                                                    ⎥           ⎟
⎜⎢              4.0           -22.0           32.0    ⎥           ⎟
⎜⎢0  1  0  ─────────────  ─────────────  ─────────────⎥, (0, 1, 2)⎟
⎜⎢         4.0⋅λ + 310.0  4.0⋅λ + 310.0  4.0⋅λ + 310.0⎥           ⎟
⎜⎢                                                    ⎥           ⎟
⎜⎢             57.0          27.0 - λ     2.0⋅λ + 3.0 ⎥           ⎟
⎜⎢0  0  1   ──────────    ─────────────  ─────────────⎥           ⎟
⎝⎣          -6⋅λ - 465    2.0⋅λ + 155.0  2.0⋅λ + 155.0⎦           ⎠

为了使矩阵 $A$ 可逆，我们注意到需要满足一个条件（在分母中）：
\begin{align}
-6\lambda -465 &\neq0\\
\end{align}

解出 $\lambda$ 的值。

In [48]:
sy.solvers.solve(-6*lamb-465, lamb)

所以这是导致矩阵可逆的 $\lambda$ 值之一。让我们用行列式来检验。如果 $| A|=0$，那么矩阵不可逆。不用担心行列式，我们会回到这个问题。

In [49]:
A = np.array([[3, -155/2, 1], [2, -1, 6], [1, 9, 4]])
np.linalg.det(A)

行列式 $| A|$ 等于 $0$。

所以我们找到了一个条件，只要 $\lambda \neq -\frac{155}{2}$，矩阵 $A$ 就是可逆的。

## <font face="gotham" color="purple"> 逆矩阵的性质 </font>

1. 如果 $A$ 和 $B$ 都是可逆的，则 $(AB)^{-1}=B^{-1}A^{-1}$。
2. 如果 $A$ 可逆，则 $(A^T)^{-1}=(A^{-1})^T$。
3. 如果 $A$ 和 $B$ 都是可逆的，并且对称，即 $AB=BA$，那么 $A^{-1}B$ 是对称的。

第一个性质很直接
\begin{align}
ABB^{-1}A^{-1}=AIA^{-1}=I=AB(AB)^{-1}
\end{align}

第二个性质是
$$
A^T(A^{-1})^T = I
$$
我们可以利用转置的性质
$$
A^T(A^{-1})^T=(A^{-1}A)^T = I^T = I
$$

第三个性质是
$$
A^{-1}B = (A^{-1}B)^T
$$
再次利用转置的性质
$$
(A^{-1}B)^{T}=B^T(A^{-1})^T=B(A^T)^{-1}=BA^{-1}
$$
我们使用 $AB = BA$ 的条件来进行
\begin{align}
AB&=BA\\
A^{-1}ABA^{-1}&=A^{-1}BAA^{-1}\\
BA^{-1}&=A^{-1}B
\end{align}
将上一个方程代入，我们得到
$$
(A^{-1}B)^{T}=BA^{-1}=A^{-1}B
$$